In [2]:
import tensorflow as tf
import numpy as np

2024-03-29 12:23:01.357645: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-29 12:23:02.241921: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [3]:
zero_d_tensor = tf.constant(4)
zero_d_tensor

2024-03-29 12:23:03.564532: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:984] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-29 12:23:03.564795: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2251] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [4]:
one_d_tensor = tf.constant([1, 2, 3, 4])
one_d_tensor

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [5]:
two_d_tensor = tf.stack([one_d_tensor, one_d_tensor])
two_d_tensor

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [1, 2, 3, 4]], dtype=int32)>

In [6]:
three_d_tensor = tf.stack([two_d_tensor, two_d_tensor, two_d_tensor])
three_d_tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]], dtype=int32)>

In [7]:
four_d_tensor = tf.stack([three_d_tensor, three_d_tensor, three_d_tensor])
four_d_tensor

<tf.Tensor: shape=(3, 3, 2, 4), dtype=int32, numpy=
array([[[[1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4]]],


       [[[1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4]]],


       [[[1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4]]]], dtype=int32)>

In [8]:
casted_tensor = tf.cast(four_d_tensor, tf.float32)
casted_tensor

<tf.Tensor: shape=(3, 3, 2, 4), dtype=float32, numpy=
array([[[[1., 2., 3., 4.],
         [1., 2., 3., 4.]],

        [[1., 2., 3., 4.],
         [1., 2., 3., 4.]],

        [[1., 2., 3., 4.],
         [1., 2., 3., 4.]]],


       [[[1., 2., 3., 4.],
         [1., 2., 3., 4.]],

        [[1., 2., 3., 4.],
         [1., 2., 3., 4.]],

        [[1., 2., 3., 4.],
         [1., 2., 3., 4.]]],


       [[[1., 2., 3., 4.],
         [1., 2., 3., 4.]],

        [[1., 2., 3., 4.],
         [1., 2., 3., 4.]],

        [[1., 2., 3., 4.],
         [1., 2., 3., 4.]]]], dtype=float32)>

In [9]:
bool_tensor = tf.constant([True, False, False, True])
bool_tensor

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False, False,  True])>

In [10]:
np_array = np.array([1, 2, 3, 4])
np_tensor = tf.constant(np_array)
np_tensor

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [11]:
fill_tensor = tf.fill([2, 2], 99)
fill_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99]], dtype=int32)>

In [12]:
ones_tensor = tf.ones_like(fill_tensor)
ones_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [16]:
random_tensor = tf.random.normal([3, 3], mean=0.0, stddev=1.0, dtype=tf.dtypes.float32, seed=None, name=None)
random_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.7813698 , -1.6791564 ,  0.69684   ],
       [-0.23464306, -0.67318845,  0.39973015],
       [-0.22127087, -1.0170566 , -1.165577  ]], dtype=float32)>

In [18]:
uniform_tensor = tf.random.uniform([3,], minval=0, maxval=1, dtype=tf.dtypes.float32, seed=None, name=None)
uniform_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.6634451 , 0.31734753, 0.4829278 ], dtype=float32)>

In [23]:
tensor_indexed = tf.constant([1,2,3,4,5,6,7,8,9])
tensor_indexed[0:3]


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [24]:
tensor_indexed[0:3+1]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [25]:
two_d_tensor[0:2, 0:1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [1]], dtype=int32)>

In [28]:
three_d_tensor[0:1, ..., 0:1]

<tf.Tensor: shape=(1, 2, 1), dtype=int32, numpy=
array([[[1],
        [1]]], dtype=int32)>